### PR TITLE
info() removed

### PR DESCRIPTION
**Pull request by randyzwitch**
This is speculative for working, fixing by looking at error the appveyor provided me

info() replaced by <at>info, platform_key() deprecated for platform_key_abi()

### CODE REVIEW

**Comment by randyzwitch** [comment]
appveyor.yml was pointing at 0.6, so updated that as well

**Comment by randyzwitch** [comment]
@tanmaykm Unfortunately now Travis is complaining about C++, so not sure how to proceed. Tried to fix Windows, ended up finding Linux/OSX broken

**Comment by tanmaykm** [comment]
It probably needed updating to a newer BinaryBuilder version. Could you try with the changes in #47 ?

**Comment by randyzwitch** [comment]
@tanmaykm Looks like this is ready for merging and a new tag

**Comment by tanmaykm** [comment]
:+1: great!

**Comment by tanmaykm** [comment]
Tagged v0.6.0 here https://github.com/JuliaLang/METADATA.jl/pull/18944

**Pull request merged**
